package he_thong_tu_van_benh_xuong_khop__thi_chtdttt.repository;

import com.github.fabiomaffioletti.firebase.repository.DefaultFirebaseRealtimeDatabaseRepository;
import he_thong_tu_van_benh_xuong_khop__thi_chtdttt.entity.Disease;
import org.springframework.stereotype.Repository;

@Repository
public class DiseaseRepository extends DefaultFirebaseRealtimeDatabaseRepository<Disease, Integer> {
}